// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxtgcvdpkuqevwcckuhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dGdjdmRwa3VxZXZ3Y2NrdWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzI4MDQsImV4cCI6MjA2NDcwODgwNH0.KXbn10_EP6EzBvg8BZxGkTiS-qLIshm0eKfQtUo11Bo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);